---
# dataverse/tasks/dataverse-solr.yml

- name: ensure EPEL repository for RedHat/CentOS 7
  yum: name=epel-release state=latest
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"

- name: install Solr pre-reqs for RedHat/CentOS 7
  yum: name="{{item}}" state=latest
  with_items:
    - java-1.8.0-openjdk-devel
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"

- name: create solr service group
  group: name={{ dataverse.solr.group }} state=present
  when: dataverse.solr.group != "root"

- name: create solr service account
  user: name={{ dataverse.solr.user }} group={{ dataverse.solr.group }}
        createhome=no comment="Dataverse Solr user"
  when: dataverse.solr.user != "root"

- name: download and unzip solr
  get_url: url="https://archive.apache.org/dist/lucene/solr/{{ dataverse.solr.version }}/solr-{{ dataverse.solr.version }}.tgz" dest=/tmp

- name: untar solr
  shell: "tar xvzC /tmp -f /tmp/solr-{{ dataverse.solr.version }}.tgz"

- name: remove solr root directory
  file: path="{{ dataverse.solr.root }}" state=absent

- name: create solr root directory exists
  file: path="{{ dataverse.solr.root }}" state=directory
        owner=root group=root mode=0755

- name: copy solr distro files into solr root
  shell: "/bin/cp -r /tmp/solr-{{ dataverse.solr.version }}/* {{ dataverse.solr.root }}"

- name: solr user needs to own some of the subdirectories to run non-root
  file: path="{{ item }}" state=directory recurse=yes
        owner="{{ dataverse.solr.user }}" group="{{ dataverse.solr.group }}"
  with_items:
    - "{{ dataverse.solr.root }}/example/logs/"
    - "{{ dataverse.solr.root }}/example/solr-webapp/"
    - "{{ dataverse.solr.root }}/example/solr/collection1/data/"

- name: clean up solr distro files
  file: path="/tmp/solr-{{ dataverse.solr.version }}" state=absent

- name: get last major solr schema
  get_url: url="https://raw.githubusercontent.com/IQSS/dataverse/develop/conf/solr/7.2.1/schema.xml"
        dest={{ dataverse.solr.root }}/example/solr/collection1/conf/
        owner=root group=root mode=0644

- name: get updated solr config
  get_url: url="https://raw.githubusercontent.com/IQSS/dataverse/develop/conf/solr/7.2.1/solrconfig.xml"
        dest={{ dataverse.solr.root }}/example/solr/collection1/conf/
        owner=root group=root mode=0644

- name: bump requestHeaderSize in jetty.xml
  lineinfile: dest={{ dataverse.solr.root }}/example/etc/jetty.xml insertafter="org.eclipse.jetty.server.bio.SocketConnector"
        line="            <Set name=\"requestHeaderSize\">102400</Set>"

- name: install solr upstart script for Debian/Ubuntu
  copy: src=solr.conf dest=/etc/init owner=root group=root mode=0644
  when: ansible_os_family == "Debian"

- name: install solr systemd conf file for RedHat/CentOS
  template: src=solr.service.j2 dest=/usr/lib/systemd/system/solr.service
        owner=root group=root mode=0644
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"

- name: reload systemd
  shell: systemctl daemon-reload
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"

- name: enable solr on boot, start solr
  service: name=solr enabled=yes state=started
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"
